/* This file was generated by generate-wire.py */
/* Do not modify this file! Modify the _csv file it was generated from. */
#include "devtools/gen_print_wire.h"
#include <ccan/mem/mem.h>
#include <ccan/tal/str/str.h>
#include <common/utils.h>
#include <stdio.h>

void print_message(const u8 *msg)
{
	switch ((enum wire_type)fromwire_peektype(msg)) {
	case WIRE_INIT: printf("WIRE_INIT:\n"); printwire_init(msg); return;
	case WIRE_ERROR: printf("WIRE_ERROR:\n"); printwire_error(msg); return;
	case WIRE_PING: printf("WIRE_PING:\n"); printwire_ping(msg); return;
	case WIRE_PONG: printf("WIRE_PONG:\n"); printwire_pong(msg); return;
	case WIRE_OPEN_CHANNEL: printf("WIRE_OPEN_CHANNEL:\n"); printwire_open_channel(msg); return;
	case WIRE_ACCEPT_CHANNEL: printf("WIRE_ACCEPT_CHANNEL:\n"); printwire_accept_channel(msg); return;
	case WIRE_FUNDING_CREATED: printf("WIRE_FUNDING_CREATED:\n"); printwire_funding_created(msg); return;
	case WIRE_FUNDING_SIGNED: printf("WIRE_FUNDING_SIGNED:\n"); printwire_funding_signed(msg); return;
	case WIRE_FUNDING_LOCKED: printf("WIRE_FUNDING_LOCKED:\n"); printwire_funding_locked(msg); return;
	case WIRE_SHUTDOWN: printf("WIRE_SHUTDOWN:\n"); printwire_shutdown(msg); return;
	case WIRE_CLOSING_SIGNED: printf("WIRE_CLOSING_SIGNED:\n"); printwire_closing_signed(msg); return;
	case WIRE_UPDATE_ADD_HTLC: printf("WIRE_UPDATE_ADD_HTLC:\n"); printwire_update_add_htlc(msg); return;
	case WIRE_UPDATE_FULFILL_HTLC: printf("WIRE_UPDATE_FULFILL_HTLC:\n"); printwire_update_fulfill_htlc(msg); return;
	case WIRE_UPDATE_FAIL_HTLC: printf("WIRE_UPDATE_FAIL_HTLC:\n"); printwire_update_fail_htlc(msg); return;
	case WIRE_UPDATE_FAIL_MALFORMED_HTLC: printf("WIRE_UPDATE_FAIL_MALFORMED_HTLC:\n"); printwire_update_fail_malformed_htlc(msg); return;
	case WIRE_COMMITMENT_SIGNED: printf("WIRE_COMMITMENT_SIGNED:\n"); printwire_commitment_signed(msg); return;
	case WIRE_REVOKE_AND_ACK: printf("WIRE_REVOKE_AND_ACK:\n"); printwire_revoke_and_ack(msg); return;
	case WIRE_UPDATE_FEE: printf("WIRE_UPDATE_FEE:\n"); printwire_update_fee(msg); return;
	case WIRE_CHANNEL_REESTABLISH: printf("WIRE_CHANNEL_REESTABLISH:\n"); printwire_channel_reestablish(msg); return;
	case WIRE_ANNOUNCEMENT_SIGNATURES: printf("WIRE_ANNOUNCEMENT_SIGNATURES:\n"); printwire_announcement_signatures(msg); return;
	case WIRE_CHANNEL_ANNOUNCEMENT: printf("WIRE_CHANNEL_ANNOUNCEMENT:\n"); printwire_channel_announcement(msg); return;
	case WIRE_NODE_ANNOUNCEMENT: printf("WIRE_NODE_ANNOUNCEMENT:\n"); printwire_node_announcement(msg); return;
	case WIRE_CHANNEL_UPDATE: printf("WIRE_CHANNEL_UPDATE:\n"); printwire_channel_update(msg); return;
	case WIRE_QUERY_SHORT_CHANNEL_IDS: printf("WIRE_QUERY_SHORT_CHANNEL_IDS:\n"); printwire_query_short_channel_ids(msg); return;
	case WIRE_REPLY_SHORT_CHANNEL_IDS_END: printf("WIRE_REPLY_SHORT_CHANNEL_IDS_END:\n"); printwire_reply_short_channel_ids_end(msg); return;
	case WIRE_QUERY_CHANNEL_RANGE: printf("WIRE_QUERY_CHANNEL_RANGE:\n"); printwire_query_channel_range(msg); return;
	case WIRE_REPLY_CHANNEL_RANGE: printf("WIRE_REPLY_CHANNEL_RANGE:\n"); printwire_reply_channel_range(msg); return;
	case WIRE_GOSSIP_TIMESTAMP_FILTER: printf("WIRE_GOSSIP_TIMESTAMP_FILTER:\n"); printwire_gossip_timestamp_filter(msg); return;
	}

	printf("UNKNOWN: %s\n", tal_hex(msg, msg));
}

void printwire_init(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_INIT) {
		printf("WRONG TYPE?!\n");
		return;
	}

	u16 gflen = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("globalfeatures=");
	printwire_u8_array(&cursor, &plen, gflen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	u16 lflen = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("localfeatures=");
	printwire_u8_array(&cursor, &plen, lflen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_error(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_ERROR) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	u16 len = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("data=");
	printwire_u8_array(&cursor, &plen, len);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_ping(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_PING) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("num_pong_bytes=");
	u16 num_pong_bytes = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&num_pong_bytes);
	u16 byteslen = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("ignored=");
	printwire_u8_array(&cursor, &plen, byteslen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_pong(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_PONG) {
		printf("WRONG TYPE?!\n");
		return;
	}

	u16 byteslen = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("ignored=");
	printwire_u8_array(&cursor, &plen, byteslen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_open_channel(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_OPEN_CHANNEL) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("chain_hash=");
	struct bitcoin_blkid chain_hash;
	fromwire_bitcoin_blkid(&cursor, &plen, &chain_hash);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_bitcoin_blkid(&chain_hash);
	printf("temporary_channel_id=");
	struct channel_id temporary_channel_id;
	fromwire_channel_id(&cursor, &plen, &temporary_channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&temporary_channel_id);
	printf("funding_satoshis=");
	u64 funding_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&funding_satoshis);
	printf("push_msat=");
	u64 push_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&push_msat);
	printf("dust_limit_satoshis=");
	u64 dust_limit_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&dust_limit_satoshis);
	printf("max_htlc_value_in_flight_msat=");
	u64 max_htlc_value_in_flight_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&max_htlc_value_in_flight_msat);
	printf("channel_reserve_satoshis=");
	u64 channel_reserve_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&channel_reserve_satoshis);
	printf("htlc_minimum_msat=");
	u64 htlc_minimum_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&htlc_minimum_msat);
	printf("feerate_per_kw=");
	u32 feerate_per_kw = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&feerate_per_kw);
	printf("to_self_delay=");
	u16 to_self_delay = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&to_self_delay);
	printf("max_accepted_htlcs=");
	u16 max_accepted_htlcs = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&max_accepted_htlcs);
	printf("funding_pubkey=");
	struct pubkey funding_pubkey;
	fromwire_pubkey(&cursor, &plen, &funding_pubkey);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&funding_pubkey);
	printf("revocation_basepoint=");
	struct pubkey revocation_basepoint;
	fromwire_pubkey(&cursor, &plen, &revocation_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&revocation_basepoint);
	printf("payment_basepoint=");
	struct pubkey payment_basepoint;
	fromwire_pubkey(&cursor, &plen, &payment_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&payment_basepoint);
	printf("delayed_payment_basepoint=");
	struct pubkey delayed_payment_basepoint;
	fromwire_pubkey(&cursor, &plen, &delayed_payment_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&delayed_payment_basepoint);
	printf("htlc_basepoint=");
	struct pubkey htlc_basepoint;
	fromwire_pubkey(&cursor, &plen, &htlc_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&htlc_basepoint);
	printf("first_per_commitment_point=");
	struct pubkey first_per_commitment_point;
	fromwire_pubkey(&cursor, &plen, &first_per_commitment_point);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&first_per_commitment_point);
	printf("channel_flags=");
	u8 channel_flags = fromwire_u8(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u8(&channel_flags);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_accept_channel(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_ACCEPT_CHANNEL) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("temporary_channel_id=");
	struct channel_id temporary_channel_id;
	fromwire_channel_id(&cursor, &plen, &temporary_channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&temporary_channel_id);
	printf("dust_limit_satoshis=");
	u64 dust_limit_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&dust_limit_satoshis);
	printf("max_htlc_value_in_flight_msat=");
	u64 max_htlc_value_in_flight_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&max_htlc_value_in_flight_msat);
	printf("channel_reserve_satoshis=");
	u64 channel_reserve_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&channel_reserve_satoshis);
	printf("htlc_minimum_msat=");
	u64 htlc_minimum_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&htlc_minimum_msat);
	printf("minimum_depth=");
	u32 minimum_depth = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&minimum_depth);
	printf("to_self_delay=");
	u16 to_self_delay = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&to_self_delay);
	printf("max_accepted_htlcs=");
	u16 max_accepted_htlcs = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&max_accepted_htlcs);
	printf("funding_pubkey=");
	struct pubkey funding_pubkey;
	fromwire_pubkey(&cursor, &plen, &funding_pubkey);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&funding_pubkey);
	printf("revocation_basepoint=");
	struct pubkey revocation_basepoint;
	fromwire_pubkey(&cursor, &plen, &revocation_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&revocation_basepoint);
	printf("payment_basepoint=");
	struct pubkey payment_basepoint;
	fromwire_pubkey(&cursor, &plen, &payment_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&payment_basepoint);
	printf("delayed_payment_basepoint=");
	struct pubkey delayed_payment_basepoint;
	fromwire_pubkey(&cursor, &plen, &delayed_payment_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&delayed_payment_basepoint);
	printf("htlc_basepoint=");
	struct pubkey htlc_basepoint;
	fromwire_pubkey(&cursor, &plen, &htlc_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&htlc_basepoint);
	printf("first_per_commitment_point=");
	struct pubkey first_per_commitment_point;
	fromwire_pubkey(&cursor, &plen, &first_per_commitment_point);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&first_per_commitment_point);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_funding_created(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_FUNDING_CREATED) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("temporary_channel_id=");
	struct channel_id temporary_channel_id;
	fromwire_channel_id(&cursor, &plen, &temporary_channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&temporary_channel_id);
	printf("funding_txid=");
	struct bitcoin_txid funding_txid;
	fromwire_bitcoin_txid(&cursor, &plen, &funding_txid);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_bitcoin_txid(&funding_txid);
	printf("funding_output_index=");
	u16 funding_output_index = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&funding_output_index);
	printf("signature=");
	secp256k1_ecdsa_signature signature;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &signature);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&signature);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_funding_signed(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_FUNDING_SIGNED) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("signature=");
	secp256k1_ecdsa_signature signature;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &signature);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&signature);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_funding_locked(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_FUNDING_LOCKED) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("next_per_commitment_point=");
	struct pubkey next_per_commitment_point;
	fromwire_pubkey(&cursor, &plen, &next_per_commitment_point);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&next_per_commitment_point);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_shutdown(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_SHUTDOWN) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	u16 len = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("scriptpubkey=");
	printwire_u8_array(&cursor, &plen, len);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_closing_signed(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_CLOSING_SIGNED) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("fee_satoshis=");
	u64 fee_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&fee_satoshis);
	printf("signature=");
	secp256k1_ecdsa_signature signature;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &signature);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&signature);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_update_add_htlc(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_UPDATE_ADD_HTLC) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("id=");
	u64 id = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&id);
	printf("amount_msat=");
	u64 amount_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&amount_msat);
	printf("payment_hash=");
	struct sha256 payment_hash;
	fromwire_sha256(&cursor, &plen, &payment_hash);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_sha256(&payment_hash);
	printf("cltv_expiry=");
	u32 cltv_expiry = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&cltv_expiry);
	printf("onion_routing_packet=");
	printwire_u8_array(&cursor, &plen, 1366);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_update_fulfill_htlc(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_UPDATE_FULFILL_HTLC) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("id=");
	u64 id = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&id);
	printf("payment_preimage=");
	struct preimage payment_preimage;
	fromwire_preimage(&cursor, &plen, &payment_preimage);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_preimage(&payment_preimage);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_update_fail_htlc(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_UPDATE_FAIL_HTLC) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("id=");
	u64 id = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&id);
	u16 len = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("reason=");
	printwire_u8_array(&cursor, &plen, len);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_update_fail_malformed_htlc(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_UPDATE_FAIL_MALFORMED_HTLC) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("id=");
	u64 id = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&id);
	printf("sha256_of_onion=");
	struct sha256 sha256_of_onion;
	fromwire_sha256(&cursor, &plen, &sha256_of_onion);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_sha256(&sha256_of_onion);
	printf("failure_code=");
	u16 failure_code = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&failure_code);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_commitment_signed(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_COMMITMENT_SIGNED) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("signature=");
	secp256k1_ecdsa_signature signature;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &signature);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&signature);
	u16 num_htlcs = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("htlc_signature=");
	printf("[");
	for (size_t i = 0; i < num_htlcs; i++) {
		secp256k1_ecdsa_signature v;
		fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &v);
		if (!cursor) {
			printf("**TRUNCATED**\n");
			return;
		}
		printwire_secp256k1_ecdsa_signature(&v);
	}
	printf("]");
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_revoke_and_ack(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_REVOKE_AND_ACK) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("per_commitment_secret=");
	struct sha256 per_commitment_secret;
	fromwire_sha256(&cursor, &plen, &per_commitment_secret);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_sha256(&per_commitment_secret);
	printf("next_per_commitment_point=");
	struct pubkey next_per_commitment_point;
	fromwire_pubkey(&cursor, &plen, &next_per_commitment_point);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&next_per_commitment_point);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_update_fee(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_UPDATE_FEE) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("feerate_per_kw=");
	u32 feerate_per_kw = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&feerate_per_kw);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_channel_reestablish(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNEL_REESTABLISH) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("next_local_commitment_number=");
	u64 next_local_commitment_number = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&next_local_commitment_number);
	printf("next_remote_revocation_number=");
	u64 next_remote_revocation_number = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&next_remote_revocation_number);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_announcement_signatures(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_ANNOUNCEMENT_SIGNATURES) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("short_channel_id=");
	struct short_channel_id short_channel_id;
	fromwire_short_channel_id(&cursor, &plen, &short_channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_short_channel_id(&short_channel_id);
	printf("node_signature=");
	secp256k1_ecdsa_signature node_signature;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &node_signature);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&node_signature);
	printf("bitcoin_signature=");
	secp256k1_ecdsa_signature bitcoin_signature;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &bitcoin_signature);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&bitcoin_signature);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_channel_announcement(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNEL_ANNOUNCEMENT) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("node_signature_1=");
	secp256k1_ecdsa_signature node_signature_1;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &node_signature_1);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&node_signature_1);
	printf("node_signature_2=");
	secp256k1_ecdsa_signature node_signature_2;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &node_signature_2);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&node_signature_2);
	printf("bitcoin_signature_1=");
	secp256k1_ecdsa_signature bitcoin_signature_1;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &bitcoin_signature_1);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&bitcoin_signature_1);
	printf("bitcoin_signature_2=");
	secp256k1_ecdsa_signature bitcoin_signature_2;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &bitcoin_signature_2);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&bitcoin_signature_2);
	u16 len = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("features=");
	printwire_u8_array(&cursor, &plen, len);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("chain_hash=");
	struct bitcoin_blkid chain_hash;
	fromwire_bitcoin_blkid(&cursor, &plen, &chain_hash);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_bitcoin_blkid(&chain_hash);
	printf("short_channel_id=");
	struct short_channel_id short_channel_id;
	fromwire_short_channel_id(&cursor, &plen, &short_channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_short_channel_id(&short_channel_id);
	printf("node_id_1=");
	struct pubkey node_id_1;
	fromwire_pubkey(&cursor, &plen, &node_id_1);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&node_id_1);
	printf("node_id_2=");
	struct pubkey node_id_2;
	fromwire_pubkey(&cursor, &plen, &node_id_2);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&node_id_2);
	printf("bitcoin_key_1=");
	struct pubkey bitcoin_key_1;
	fromwire_pubkey(&cursor, &plen, &bitcoin_key_1);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&bitcoin_key_1);
	printf("bitcoin_key_2=");
	struct pubkey bitcoin_key_2;
	fromwire_pubkey(&cursor, &plen, &bitcoin_key_2);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&bitcoin_key_2);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_node_announcement(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_NODE_ANNOUNCEMENT) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("signature=");
	secp256k1_ecdsa_signature signature;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &signature);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&signature);
	u16 flen = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("features=");
	printwire_u8_array(&cursor, &plen, flen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("timestamp=");
	u32 timestamp = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&timestamp);
	printf("node_id=");
	struct pubkey node_id;
	fromwire_pubkey(&cursor, &plen, &node_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&node_id);
	printf("rgb_color=");
	printwire_u8_array(&cursor, &plen, 3);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("alias=");
	printwire_u8_array(&cursor, &plen, 32);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	u16 addrlen = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("addresses=");
	printwire_u8_array(&cursor, &plen, addrlen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_channel_update(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNEL_UPDATE) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("signature=");
	secp256k1_ecdsa_signature signature;
	fromwire_secp256k1_ecdsa_signature(&cursor, &plen, &signature);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_secp256k1_ecdsa_signature(&signature);
	printf("chain_hash=");
	struct bitcoin_blkid chain_hash;
	fromwire_bitcoin_blkid(&cursor, &plen, &chain_hash);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_bitcoin_blkid(&chain_hash);
	printf("short_channel_id=");
	struct short_channel_id short_channel_id;
	fromwire_short_channel_id(&cursor, &plen, &short_channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_short_channel_id(&short_channel_id);
	printf("timestamp=");
	u32 timestamp = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&timestamp);
	printf("flags=");
	u16 flags = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&flags);
	printf("cltv_expiry_delta=");
	u16 cltv_expiry_delta = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&cltv_expiry_delta);
	printf("htlc_minimum_msat=");
	u64 htlc_minimum_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&htlc_minimum_msat);
	printf("fee_base_msat=");
	u32 fee_base_msat = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&fee_base_msat);
	printf("fee_proportional_millionths=");
	u32 fee_proportional_millionths = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&fee_proportional_millionths);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_query_short_channel_ids(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_QUERY_SHORT_CHANNEL_IDS) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("chain_hash=");
	struct bitcoin_blkid chain_hash;
	fromwire_bitcoin_blkid(&cursor, &plen, &chain_hash);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_bitcoin_blkid(&chain_hash);
	u16 len = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("encoded_short_ids=");
	printwire_u8_array(&cursor, &plen, len);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_reply_short_channel_ids_end(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_REPLY_SHORT_CHANNEL_IDS_END) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("chain_hash=");
	struct bitcoin_blkid chain_hash;
	fromwire_bitcoin_blkid(&cursor, &plen, &chain_hash);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_bitcoin_blkid(&chain_hash);
	printf("complete=");
	u8 complete = fromwire_u8(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u8(&complete);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_query_channel_range(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_QUERY_CHANNEL_RANGE) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("chain_hash=");
	struct bitcoin_blkid chain_hash;
	fromwire_bitcoin_blkid(&cursor, &plen, &chain_hash);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_bitcoin_blkid(&chain_hash);
	printf("first_blocknum=");
	u32 first_blocknum = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&first_blocknum);
	printf("number_of_blocks=");
	u32 number_of_blocks = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&number_of_blocks);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_reply_channel_range(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_REPLY_CHANNEL_RANGE) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("chain_hash=");
	struct bitcoin_blkid chain_hash;
	fromwire_bitcoin_blkid(&cursor, &plen, &chain_hash);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_bitcoin_blkid(&chain_hash);
	printf("first_blocknum=");
	u32 first_blocknum = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&first_blocknum);
	printf("number_of_blocks=");
	u32 number_of_blocks = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&number_of_blocks);
	printf("complete=");
	u8 complete = fromwire_u8(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u8(&complete);
	u16 len = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printf("encoded_short_ids=");
	printwire_u8_array(&cursor, &plen, len);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_gossip_timestamp_filter(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_GOSSIP_TIMESTAMP_FILTER) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("chain_hash=");
	struct bitcoin_blkid chain_hash;
	fromwire_bitcoin_blkid(&cursor, &plen, &chain_hash);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_bitcoin_blkid(&chain_hash);
	printf("first_timestamp=");
	u32 first_timestamp = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&first_timestamp);
	printf("timestamp_range=");
	u32 timestamp_range = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&timestamp_range);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_open_channel_option_upfront_shutdown_script(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_OPEN_CHANNEL) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("chain_hash=");
	struct bitcoin_blkid chain_hash;
	fromwire_bitcoin_blkid(&cursor, &plen, &chain_hash);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_bitcoin_blkid(&chain_hash);
	printf("temporary_channel_id=");
	struct channel_id temporary_channel_id;
	fromwire_channel_id(&cursor, &plen, &temporary_channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&temporary_channel_id);
	printf("funding_satoshis=");
	u64 funding_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&funding_satoshis);
	printf("push_msat=");
	u64 push_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&push_msat);
	printf("dust_limit_satoshis=");
	u64 dust_limit_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&dust_limit_satoshis);
	printf("max_htlc_value_in_flight_msat=");
	u64 max_htlc_value_in_flight_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&max_htlc_value_in_flight_msat);
	printf("channel_reserve_satoshis=");
	u64 channel_reserve_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&channel_reserve_satoshis);
	printf("htlc_minimum_msat=");
	u64 htlc_minimum_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&htlc_minimum_msat);
	printf("feerate_per_kw=");
	u32 feerate_per_kw = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&feerate_per_kw);
	printf("to_self_delay=");
	u16 to_self_delay = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&to_self_delay);
	printf("max_accepted_htlcs=");
	u16 max_accepted_htlcs = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&max_accepted_htlcs);
	printf("funding_pubkey=");
	struct pubkey funding_pubkey;
	fromwire_pubkey(&cursor, &plen, &funding_pubkey);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&funding_pubkey);
	printf("revocation_basepoint=");
	struct pubkey revocation_basepoint;
	fromwire_pubkey(&cursor, &plen, &revocation_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&revocation_basepoint);
	printf("payment_basepoint=");
	struct pubkey payment_basepoint;
	fromwire_pubkey(&cursor, &plen, &payment_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&payment_basepoint);
	printf("delayed_payment_basepoint=");
	struct pubkey delayed_payment_basepoint;
	fromwire_pubkey(&cursor, &plen, &delayed_payment_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&delayed_payment_basepoint);
	printf("htlc_basepoint=");
	struct pubkey htlc_basepoint;
	fromwire_pubkey(&cursor, &plen, &htlc_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&htlc_basepoint);
	printf("first_per_commitment_point=");
	struct pubkey first_per_commitment_point;
	fromwire_pubkey(&cursor, &plen, &first_per_commitment_point);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&first_per_commitment_point);
	printf("channel_flags=");
	u8 channel_flags = fromwire_u8(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u8(&channel_flags);
	printf("shutdown_len=");
	u16 shutdown_len = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&shutdown_len);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_accept_channel_option_upfront_shutdown_script(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_ACCEPT_CHANNEL) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("temporary_channel_id=");
	struct channel_id temporary_channel_id;
	fromwire_channel_id(&cursor, &plen, &temporary_channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&temporary_channel_id);
	printf("dust_limit_satoshis=");
	u64 dust_limit_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&dust_limit_satoshis);
	printf("max_htlc_value_in_flight_msat=");
	u64 max_htlc_value_in_flight_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&max_htlc_value_in_flight_msat);
	printf("channel_reserve_satoshis=");
	u64 channel_reserve_satoshis = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&channel_reserve_satoshis);
	printf("htlc_minimum_msat=");
	u64 htlc_minimum_msat = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&htlc_minimum_msat);
	printf("minimum_depth=");
	u32 minimum_depth = fromwire_u32(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u32(&minimum_depth);
	printf("to_self_delay=");
	u16 to_self_delay = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&to_self_delay);
	printf("max_accepted_htlcs=");
	u16 max_accepted_htlcs = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&max_accepted_htlcs);
	printf("funding_pubkey=");
	struct pubkey funding_pubkey;
	fromwire_pubkey(&cursor, &plen, &funding_pubkey);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&funding_pubkey);
	printf("revocation_basepoint=");
	struct pubkey revocation_basepoint;
	fromwire_pubkey(&cursor, &plen, &revocation_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&revocation_basepoint);
	printf("payment_basepoint=");
	struct pubkey payment_basepoint;
	fromwire_pubkey(&cursor, &plen, &payment_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&payment_basepoint);
	printf("delayed_payment_basepoint=");
	struct pubkey delayed_payment_basepoint;
	fromwire_pubkey(&cursor, &plen, &delayed_payment_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&delayed_payment_basepoint);
	printf("htlc_basepoint=");
	struct pubkey htlc_basepoint;
	fromwire_pubkey(&cursor, &plen, &htlc_basepoint);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&htlc_basepoint);
	printf("first_per_commitment_point=");
	struct pubkey first_per_commitment_point;
	fromwire_pubkey(&cursor, &plen, &first_per_commitment_point);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&first_per_commitment_point);
	printf("shutdown_len=");
	u16 shutdown_len = fromwire_u16(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u16(&shutdown_len);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}

void printwire_channel_reestablish_option_data_loss_protect(const u8 *cursor)
{
	size_t plen = tal_len(cursor);

	if (fromwire_u16(&cursor, &plen) != WIRE_CHANNEL_REESTABLISH) {
		printf("WRONG TYPE?!\n");
		return;
	}

	printf("channel_id=");
	struct channel_id channel_id;
	fromwire_channel_id(&cursor, &plen, &channel_id);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_channel_id(&channel_id);
	printf("next_local_commitment_number=");
	u64 next_local_commitment_number = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&next_local_commitment_number);
	printf("next_remote_revocation_number=");
	u64 next_remote_revocation_number = fromwire_u64(&cursor, &plen);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_u64(&next_remote_revocation_number);
	printf("your_last_per_commitment_secret=");
	struct sha256 your_last_per_commitment_secret;
	fromwire_sha256(&cursor, &plen, &your_last_per_commitment_secret);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_sha256(&your_last_per_commitment_secret);
	printf("my_current_per_commitment_point=");
	struct pubkey my_current_per_commitment_point;
	fromwire_pubkey(&cursor, &plen, &my_current_per_commitment_point);
	if (!cursor) {
		printf("**TRUNCATED**\n");
		return;
	}
	printwire_pubkey(&my_current_per_commitment_point);

	if (plen != 0)
		printf("EXTRA: %s\n", tal_hexstr(NULL, cursor, plen));
}


